### ISSUE TITLE
Would you welcome these contributions and be willing to adjust the package name?

### ISSUE THREAD

**Issue by jgonggrijp** [Alorel/typescript-proto-decorator#18]
Thank you @Alorel for providing this useful package.

I'm planning to release a package that provides a few decorators for Backbone. At first, I was planning to include my own `@proto` implementation, but I quickly realised there might already exist one. I found yours on the NPM package index.

I would like to drop my own implementation and use your package instead. However, the name (`typescript-proto-decorator`) and the toolchain suggest that you are specifically targetting TypeScript. I believe the same decorators specification is followed by the [@babel/plugin-proposal-decorators](https://babeljs.io/docs/en/next/babel-plugin-proposal-decorators.html) package, so in principle, your implementation could also work with Babel.

Would you accept a pull request that adds Babel compatibility as well as compatibility checks for continuous integration?

Furthermore, would you be willing to shorten the name of your package to just `proto-decorator`, once Babel compatibility is realized?

I should add that the proposal has [evolved](https://github.com/tc39/proposal-decorators/) considerably, compared to the current implementations in TypeScript and Babel. Would you accept a pull request that makes the decorator forward-compatible with the latest version of the draft?

**Comment by Alorel** [comment]
Hey, thanks for letting me know these proposals exist (I just use Typescript to transpile my code to es5 and include polyfills through [polyfill.io](https://polyfill.io)).

I'll make a note and look into these over the weekend. In principal, I'm not opposed to supporting esnext decorators, but I'll want to read up on them first to know about any differences etc. I want this package to be as small and efficient as possible, therefore I might opt to just turn this into a monorepo with some common code and publish the es and typescript versions separately.

**Comment by jgonggrijp** [comment]
> Hey, thanks for letting me know these proposals exist [...].

Welcome.

> I'll make a note and look into these over the weekend. In principal, I'm not opposed to supporting esnext decorators, but I'll want to read up on them first to know about any differences etc. I want this package to be as small and efficient as possible, therefore I might opt to just turn this into a monorepo with some common code and publish the es and typescript versions separately.

Just to get things 100% straight, there is no "typescript version" of decorators. There is a single decorators proposal for ESnext, which has evolved over time. TypeScript and Babel both currently implement *the same old version* of this proposal, which you can still find [over here](https://github.com/wycats/javascript-decorators/blob/master/README.md). Since this old version is the only version which currently has transpiler support, this is also the version that people are currently using, including your package.

So your package is not specific to TypeScript, even though you probably got the how-to from [this page in the TypeScript handbook](http://www.typescriptlang.org/docs/handbook/decorators.html). This is why I'm suggesting to remove "typescript" from the name of your package and to add some checks so that Babel users can rest assured that your decorator will work for them, too. You are using TypeScript for the implementation of your package and you can continue doing so, but this doesn't have to prevent your users from using a different transpiler.

The latest version of this same decorators proposal is what I linked to above ([this one](https://github.com/tc39/proposal-decorators/)). At some point, transpilers will catch up and start implementing this later version. It would be nice if your decorator would continue to work in this (near) future, which is why I'm proposing to make your decorator forward-compatible.

**Comment by Alorel** [comment]
Take a look at [this PR](https://github.com/Alorel/typescript-proto-decorator/pull/19/files#diff-a304f30fd84ad5353ee71c7871cfa32f) - did I get the forward compatibility right? Seems to work fine on https://babeljs.io/repl.

**Comment by jgonggrijp** [comment]
Thanks @Alorel, I left a review. I don't think you got the forward compatibility right, but no wonder with a first blind guess in the dark (as there is currently no way to test new-style decorators).

It's uplifting (if not very surprising) to hear that your decorator appears to work with Babel as well. How about always checking this in the Travis build? Would you appreciate a pull request for that?

**Comment by Alorel** [comment]
Pushed some changes, af22ea557b4b1c4174994bb7d0bb21ea6408adc9...355f3fb7a04471b07a95dfee5b79275ef815d7d7.

A unit test PR against the dev branch would definitely be appreciated!
